company-profile:
  delta:
    group-id: ${COMPANY_PROFILE_DELTA_GROUP_ID:company-profile-delta-consumer}
    topic: ${COMPANY_PROFILE_DELTA_TOPIC:company-profile-delta}
    retry-attempts: ${COMPANY_PROFILE_DELTA_ATTEMPTS:4}
    backoff-delay: ${COMPANY_PROFILE_DELTA_BACKOFF_DELAY:100}

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}
    listener:
      concurrency: ${COMPANY_PROFILE_DELTA_LISTENER_CONCURRENCY:1}
