company-profile:
  delta:
    group-id: ${COMPANY_PROFILE_DELTA_GROUP_ID:company-profile-delta-consumer}
    topic: ${COMPANY_PROFILE_DELTA_TOPIC:company-profile-delta}
    retry-attempts: ${COMPANY_PROFILE_DELTA_ATTEMPTS:4}
    backoff-delay: ${COMPANY_PROFILE_DELTA_BACKOFF_DELAY:10000}

spring:
  kafka:
    bootstrap-servers: ${DATA_SYNC_KAFKA_BROKER_URL:localhost:9092}
    listener:
      concurrency: ${COMPANY_PROFILE_DELTA_LISTENER_CONCURRENCY:1}

wiremock:
  server:
    port: 8888

api:
  company-profile-api-key: ${COMPANY_PROFILE_API_KEY:localhost}
  api-url: ${API_URL:http://localhost:8888}
  internal-api-url: ${INTERNAL_API_URL:localhost}
